builds:
  - goos:
    - linux
    - darwin
    - windows

brews:
  - tap:
      owner: Justintime50
      name: homebrew-formulas
    folder: formula
    homepage: "https://github.com/Justintime50/alchemist"
    description: "Update, backup, and administer your Homebrew or Chocolatey instances"
    commit_author:
      name: Justintime50
      email: 39606064+Justintime50@users.noreply.github.com
